version: '3.8'
services:
  postgres:
    image: postgres:15.3
    container_name: talli_db
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - intra

  backend:
    container_name: talli_backend
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: >
      bash -c "sleep 20 &&
        npx prisma migrate deploy &&
        npm start"
    networks:
      - intra

networks:
  intra:
    driver: bridge
