version: '3.8'
services:
  backend:
    container_name: talli_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    networks:
      - intra

networks:
  intra:
    driver: bridge
