version: '3.7'
services:
  postgres:
    image: postgres:15.3
    container_name: talli_db
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432'
    networks:
      - intra
networks:
  intra:
    driver: bridge
